name: Run Tests and Generate Allure Report

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install unzip
      run: sudo apt-get update && sudo apt-get install unzip -y

    - name: Install zip
      run: sudo apt-get install zip -y

    - name: Install Allure
      run: |
        wget https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.24.0/allure-commandline-2.24.0.zip
        unzip allure-commandline-2.24.0.zip
        sudo mv allure-2.24.0 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/bin/allure

    - name: Run tests
      run: mvn clean test

    - name: Generate Allure Report
      run: allure generate target/allure-results --clean -o allure-report

    # 👉 Compress report (IMPORTANT)
    - name: Zip Allure Report
      run: zip -r allure-report.zip allure-report

    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report.zip

    # 📧 Send Email with attachment
    - name: Send Email
      uses: dawidd6/action-send-mail@v3
      continue-on-error: true
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Allure Test Report"
        to: tahakik9767@gmail.com
        from: ${{ secrets.EMAIL_USERNAME }}
        body: |
          Test execution completed successfully.

          📊 Allure report is attached (ZIP file).
          If attachment fails, download from:
          GitHub → Actions → Artifacts
        attachments: allure-report.zip
